namespace Sigcomt.Common.Enums
{
    public enum TipoArchivo
    {
        Productividad = 1,
        Monitoreo = 2,
        DiasAusencia = 3,
        GrupoSupervisorUAC = 4,
        SLA = 5,
        DataAutomotriz = 6,
        //TotalCuentas2Abono = 7,
        //MontosTrasladosCTS = 8,
        //CmrRatificada = 9,
        //SLAContactenos = 10,
        //JefeGerenteCCFF = 11,
        //InformeVentaCCFF = 12,
        RIActivosSuperCash = 13,
        //SegurosCCFF = 14,
        RICalidadCICCFF = 15,
        RICalidadNPSCCFF = 16,
        //DerivacionCCFF = 17,
        //AmpliacionesCCFF = 18,
        //PasivosCCFF = 19,
        MetaSagaRapicash = 21,
        MetaSodimacRapicash = 22,
        MetaMaestroRapicash = 23,
        //ResumenSagaRapicash = 24,
        DetalleSagaRapicash = 25,
        GanadoresMaestroRapicash = 26,
        //ResumenMaestroRapicash = 27,
        GanadoresSodimacRapicash = 28,
        CierrePlanningJefeComercial = 29,
        //PesoCCFF = 30,
        EmpleadoCCFF = 31,
        //TarjetaPromotorCCFF = 32,
        //RISeguroCCFF = 33,
        RITiempoEsperaCCFF = 34,
        RITiempoEsperaPlataforma = 35,
        RITiempoEsperaCajero = 36,
        RITarjetasAvanceZonales = 37,
        RIActivosRapicashCCFF = 38,
        //RIParticipacionSaga = 39,
        //RIParticipacionTottus = 40,
        //RIParticipacionSodimac = 41,
        //RIParticipacionMaestro = 42,
        RICalidadAtencion1erContacto = 43,
        RIAmpliacionLinea = 44,
        InfoComercial = 45,
        RIOperacionSF = 46,
        RIOperacionE = 47,
        MetaTottusRapicash = 48,
        DetalleTottusRapicash = 49,
        //ResumenSodimacRapicash = 50,
        PlanillaCajeroTottusRapicash = 51,
        RIPasivosCsdCsi = 52,
        RIDerivacionHeavyPlataformaCCFF = 53,
        //RIDerivacionHeavyPlataformaCCFFBPI = 54,
        //RIDerivacionHeavyPlataformaMulticanal = 55,
        RIDerivacionCajaAtencionesCaja = 56,
        RIDerivacionCajaMetaRetiro = 57,
        RIDerivacionCajaMetaPagoTC = 58,
        RIDerivacionCajaPagoTC = 59,
        RIDerivacionCajaRetirosTCCajaPIF = 60,
        RIDerivacionCajaRetirosTDCajaPIF = 61,
        //RIDerivacionCajaRetirosCajaPIF = 62,
        RIPasivosCortoLargoPlazo = 63,
        // RIDerivacionHeavyPlataformaCCFFBT = 64,
        //RIDerivacionHeavyPlataformaCCFFMAS = 65,
        RISeguroVSC = 66,
        //RITiempoEsperaCajeroReg = 67,
        //PlanillaMaestroRapicash = 68,
        ReferidoCCFF = 69,
        RIParticipacion = 70,
        RITiempoEspera = 71,
        
        //SodimacGanadoresRapicash = 73,
        RISeguroTP=74,
        RISeguroP1=75,
        RISeguroP2=76,
        PuntajeKPI =78,
        Bono=79,
        MantenimientoAutomotriz=80,
        RITarjetaAdicional=81,
        //RIDerivacionCajaAtencionesCajaReporte = 82,
        
        //Matenimiento Indicador de CCFF
        KPIIndicador=83,
        Indicador=84,
        HomologacionIndicador=85,
        PesoKPI=86,
        TarifarioIndicador=87,
        EscalaFormatoCCFF=88,
        PotenciarKPI=89,

        //Homologaciones
        HomologacionEmpleado=90,
        HomologacionCCFF=91,

       //Maestro Rapicash
        MaestroSagaTottus=92,
        MaestroSodimacMaestro=93



    }
}